package com.example.selfdiagnosticapp;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.view.View;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.TextView;
import android.widget.Toast;
import android.os.Bundle;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;

public class symptoms extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.symptoms);
        Intent data = getIntent();
        String username=data.getStringExtra("username");

        final Intent i = new Intent(symptoms.this,pred.class);

        TextView textView1 = (TextView)findViewById(R.id.textView6);
        textView1.setText("Hello "+username);

        List<String> symptoms= new ArrayList<String>();
        symptoms.add("--");
        symptoms.add(" Heberden's node ");
        symptoms.add(" Stahli's line ");
        symptoms.add(" abdominal tenderness ");
        symptoms.add(" abnormally hard consistency ");
        symptoms.add(" abortion ");
        symptoms.add(" abscess bacterial ");
        symptoms.add(" achalasia ");
        symptoms.add(" ache ");
        symptoms.add(" agitation ");
        symptoms.add(" alcohol binge episode ");
        symptoms.add(" ambidexterity ");
        symptoms.add(" angina pectoris ");
        symptoms.add(" apyrexial ");
        symptoms.add(" asterixis ");
        symptoms.add(" asthenia ");
        symptoms.add(" ataxia ");
        symptoms.add(" atypia ");
        symptoms.add(" aura ");
        symptoms.add(" bedridden ");
        symptoms.add(" behavior hyperactive ");
        symptoms.add(" blackout ");
        symptoms.add(" bleeding of vagina ");
        symptoms.add(" bowel sounds decreased ");
        symptoms.add(" bradycardia ");
        symptoms.add(" breakthrough pain ");
        symptoms.add(" breath sounds decreased ");
        symptoms.add(" bruit ");
        symptoms.add(" burning sensation ");
        symptoms.add(" cachexia ");
        symptoms.add(" cardiomegaly ");
        symptoms.add(" cardiovascular event ");
        symptoms.add(" cardiovascular finding ");
        symptoms.add(" catatonia ");
        symptoms.add(" chest discomfort ");
        symptoms.add(" chest tightness ");
        symptoms.add(" chill ");
        symptoms.add(" clammy skin ");
        symptoms.add(" claudication ");
        symptoms.add(" clonus ");
        symptoms.add(" consciousness clear ");
        symptoms.add(" constipation ");
        symptoms.add(" cough ");
        symptoms.add(" cushingoid facies ");
        symptoms.add(" cushingoidÂ habitus ");
        symptoms.add(" cyanosis ");
        symptoms.add(" cystic lesion ");
        symptoms.add(" debilitation ");
        symptoms.add(" decreased body weight ");
        symptoms.add(" decreased translucency ");
        symptoms.add(" diarrhea ");
        symptoms.add(" difficulty ");
        symptoms.add(" difficulty passing urine ");
        symptoms.add(" disequilibrium ");
        symptoms.add(" distended abdomen ");
        symptoms.add(" distress respiratory ");
        symptoms.add(" disturbed family ");
        symptoms.add(" dizziness ");
        symptoms.add(" dizzy spells ");
        symptoms.add(" drool ");
        symptoms.add(" drowsiness ");
        symptoms.add(" dullness ");
        symptoms.add(" dysesthesia ");
        symptoms.add(" dyspareunia ");
        symptoms.add(" dyspnea ");
        symptoms.add(" dyspnea on exertion ");
        symptoms.add(" dysuria ");
        symptoms.add(" ecchymosis ");
        symptoms.add(" egophony ");
        symptoms.add(" emphysematous change ");
        symptoms.add(" energy increased ");
        symptoms.add(" erythema ");
        symptoms.add(" estrogen use ");
        symptoms.add(" excruciating pain ");
        symptoms.add(" exhaustion ");
        symptoms.add(" extrapyramidal sign ");
        symptoms.add(" extreme exhaustion ");
        symptoms.add(" facial paresis ");
        symptoms.add(" fall ");
        symptoms.add(" fatigue ");
        symptoms.add(" feeling hopeless ");
        symptoms.add(" feeling strange ");
        symptoms.add(" feeling suicidal ");
        symptoms.add(" feels hot/feverish ");
        symptoms.add(" fever ");
        symptoms.add(" floppy ");
        symptoms.add(" food intolerance ");
        symptoms.add(" formication ");
        symptoms.add(" frail ");
        symptoms.add(" fremitus ");
        symptoms.add(" gag ");
        symptoms.add(" general discomfort ");
        symptoms.add(" general unsteadiness ");
        symptoms.add(" gravida 0 ");
        symptoms.add(" gravida 10 ");
        symptoms.add(" green sputum ");
        symptoms.add(" groggy ");
        symptoms.add(" guaiac positive ");
        symptoms.add(" gurgle ");
        symptoms.add(" hacking cough ");
        symptoms.add(" haemoptysis ");
        symptoms.add(" haemorrhage ");
        symptoms.add(" hallucinations auditory ");
        symptoms.add(" hallucinations visual ");
        symptoms.add(" has religious belief ");
        symptoms.add(" headache ");
        symptoms.add(" heartburn ");
        symptoms.add(" heavy feeling ");
        symptoms.add(" heavy legs ");
        symptoms.add(" hematocrit decreased ");
        symptoms.add(" hematuria ");
        symptoms.add(" heme positive ");
        symptoms.add(" hemianopsia homonymous ");
        symptoms.add(" hemiplegia ");
        symptoms.add(" hemodynamically stable ");
        symptoms.add(" hepatomegaly ");
        symptoms.add(" hepatosplenomegaly ");
        symptoms.add(" hirsutism ");
        symptoms.add(" history of - blackout ");
        symptoms.add(" hoarseness ");
        symptoms.add(" homelessness ");
        symptoms.add(" hot flush ");
        symptoms.add(" hunger ");
        symptoms.add(" hyperacusis ");
        symptoms.add(" hypercapnia ");
        symptoms.add(" hyperemesis ");
        symptoms.add(" hyperhidrosis disorder ");
        symptoms.add(" hyperkalemia ");
        symptoms.add(" hypersomnia ");
        symptoms.add(" hypersomnolence ");
        symptoms.add(" hypertonicity ");
        symptoms.add(" hyperventilation ");
        symptoms.add(" hypoalbuminemia ");
        symptoms.add(" hypocalcemia result ");
        symptoms.add(" hypokalemia ");
        symptoms.add(" hypokinesia ");
        symptoms.add(" hypometabolism ");
        symptoms.add(" hyponatremia ");
        symptoms.add(" hypotension ");
        symptoms.add(" hypothermia, natural ");
        symptoms.add(" hypotonic ");
        symptoms.add(" hypoxemia ");
        symptoms.add(" inappropriate affect ");
        symptoms.add(" incoherent ");
        symptoms.add(" indifferent mood ");
        symptoms.add(" intermenstrual heavy bleeding ");
        symptoms.add(" intoxication ");
        symptoms.add(" irritable mood ");
        symptoms.add(" jugular venous distention ");
        symptoms.add(" labored breathing ");
        symptoms.add(" lameness ");
        symptoms.add(" large-for-dates fetus ");
        symptoms.add(" leftÂ atrialÂ hypertrophy ");
        symptoms.add(" lesion ");
        symptoms.add(" lethargy ");
        symptoms.add(" lightheadedness ");
        symptoms.add(" lip smacking ");
        symptoms.add(" loose associations ");
        symptoms.add(" lung nodule ");
        symptoms.add(" macerated skin ");
        symptoms.add(" macule ");
        symptoms.add(" malaise ");
        symptoms.add(" mass in breast ");
        symptoms.add(" mass of body structure ");
        symptoms.add(" mediastinal shift ");
        symptoms.add(" mental status changes ");
        symptoms.add(" metastatic lesion ");
        symptoms.add(" milky ");
        symptoms.add(" moan ");
        symptoms.add(" monoclonal ");
        symptoms.add(" monocytosis ");
        symptoms.add(" mood depressed ");
        symptoms.add(" motor retardation ");
        symptoms.add(" muscle hypotonia ");
        symptoms.add(" muscle twitch ");
        symptoms.add(" myalgia ");
        symptoms.add(" mydriasis ");
        symptoms.add(" myoclonus ");
        symptoms.add(" nasal discharge present ");
        symptoms.add(" nasal flaring ");
        symptoms.add(" nausea ");
        symptoms.add(" nausea and vomiting ");
        symptoms.add(" neck stiffness ");
        symptoms.add(" nervousness ");
        symptoms.add(" night sweat ");
        symptoms.add(" nightmare ");
        symptoms.add(" no known drug allergies ");
        symptoms.add(" noisy respiration ");
        symptoms.add(" non-productive cough ");
        symptoms.add(" nonsmoker ");
        symptoms.add(" numbness ");
        symptoms.add(" numbness of hand ");
        symptoms.add(" oliguria ");
        symptoms.add(" orthopnea ");
        symptoms.add(" orthostasis ");
        symptoms.add(" out of breath ");
        symptoms.add(" overweight ");
        symptoms.add(" pain ");
        symptoms.add(" pain abdominal ");
        symptoms.add(" pain back ");
        symptoms.add(" pain chest ");
        symptoms.add(" pain foot ");
        symptoms.add(" pain in lower limb ");
        symptoms.add(" pain neck ");
        symptoms.add(" pallor ");
        symptoms.add(" palpitation ");
        symptoms.add(" para 2 ");
        symptoms.add(" paraparesis ");
        symptoms.add(" paresis ");
        symptoms.add(" paresthesia ");
        symptoms.add(" passed stones ");
        symptoms.add(" patient non compliance ");
        symptoms.add(" pin-point pupils ");
        symptoms.add(" pleuritic pain ");
        symptoms.add(" polydypsia ");
        symptoms.add(" polymyalgia ");
        symptoms.add(" polyuria ");
        symptoms.add(" poor dentition ");
        symptoms.add(" poor feeding ");
        symptoms.add(" posteriorÂ rhinorrhea ");
        symptoms.add(" posturing ");
        symptoms.add(" presence of q wave ");
        symptoms.add(" pressure chest ");
        symptoms.add(" previous pregnancies 2 ");
        symptoms.add(" primigravida ");
        symptoms.add(" productive cough ");
        symptoms.add(" projectile vomiting ");
        symptoms.add(" prostate tender ");
        symptoms.add(" prostatism ");
        symptoms.add(" proteinemia ");
        symptoms.add(" pruritus ");
        symptoms.add(" pulse absent ");
        symptoms.add(" pulsusÂ paradoxus ");
        symptoms.add(" pustule ");
        symptoms.add(" qt interval prolonged ");
        symptoms.add(" r wave feature ");
        symptoms.add(" rale ");
        symptoms.add(" rambling speech ");
        symptoms.add(" rapid shallow breathing ");
        symptoms.add(" redness ");
        symptoms.add(" regurgitates after swallowing ");
        symptoms.add(" renal angle tenderness ");
        symptoms.add(" retropulsion ");
        symptoms.add(" rhonchus ");
        symptoms.add(" rigor - temperature-associated observation ");
        symptoms.add(" satiety early ");
        symptoms.add(" scar tissue ");
        symptoms.add(" scleralÂ icterus ");
        symptoms.add(" sedentary ");
        symptoms.add(" seizure ");
        symptoms.add(" sensory discomfort ");
        symptoms.add(" shooting pain ");
        symptoms.add(" shortness of breath ");
        symptoms.add(" sinus rhythm ");
        symptoms.add(" sleeplessness ");
        symptoms.add(" sleepy ");
        symptoms.add(" sneeze ");
        symptoms.add(" snore ");
        symptoms.add(" snuffle ");
        symptoms.add(" splenomegaly ");
        symptoms.add(" spontaneous rupture of membranes ");
        symptoms.add(" stiffness ");
        symptoms.add(" stool color yellow ");
        symptoms.add(" stuffy nose ");
        symptoms.add(" suicidal ");
        symptoms.add(" sweat ");
        symptoms.add(" sweating increased ");
        symptoms.add(" swelling ");
        symptoms.add(" symptom aggravating factors ");
        symptoms.add(" syncope ");
        symptoms.add(" systolic ejection murmur ");
        symptoms.add(" systolic murmur ");
        symptoms.add(" t wave inverted ");
        symptoms.add(" tachypnea ");
        symptoms.add(" terrify ");
        symptoms.add(" thicken ");
        symptoms.add(" throat sore ");
        symptoms.add(" tired ");
        symptoms.add(" transaminitis ");
        symptoms.add(" tremor ");
        symptoms.add(" tumor cell invasion ");
        symptoms.add(" unconscious state ");
        symptoms.add(" underweight ");
        symptoms.add(" unhappy ");
        symptoms.add(" unresponsiveness ");
        symptoms.add(" unsteady gait ");
        symptoms.add(" unwell ");
        symptoms.add(" urge incontinence ");
        symptoms.add(" urinary hesitation ");
        symptoms.add(" verbal auditory hallucinations ");
        symptoms.add(" vertigo ");
        symptoms.add(" vision blurred ");
        symptoms.add(" vomiting ");
        symptoms.add(" weepiness ");
        symptoms.add(" weight gain ");
        symptoms.add(" wheelchair bound ");
        symptoms.add(" wheezing ");
        symptoms.add(" worry ");
        symptoms.add(" yellow sputum ");

        final Spinner symptom1 = findViewById(R.id.spinner2);
        Spinner int1 = findViewById(R.id.spinner4);
        final Spinner symptom2 = findViewById(R.id.spinner5);
        final Spinner symptom3 = findViewById(R.id.spinner6);
        Spinner int2 = findViewById(R.id.spinner7);
        Spinner int3 = findViewById(R.id.spinner8);
        final Spinner symptom4 = findViewById(R.id.spinner9);
        Spinner int4 = findViewById(R.id.spinner10);
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,symptoms);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        symptom1.setAdapter(adapter);
        symptom2.setAdapter(adapter);
        symptom3.setAdapter(adapter);
        symptom4.setAdapter(adapter);
        //spinner.setOnItemSelectedListener(this)
        //Toast.makeText(spinner2.getContext(),symp1, Toast.LENGTH_SHORT).show();
        List<String> intensity=new ArrayList<String>();
        intensity.add("High");
        intensity.add("Medium");
        intensity.add("Low");
        ArrayAdapter<String> adapter1 = new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,intensity);
        adapter1.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        int1.setAdapter(adapter1);
        int2.setAdapter(adapter1);
        int3.setAdapter(adapter1);
        int4.setAdapter(adapter1);
        Button bt= (Button) findViewById(R.id.button);
        bt.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String symp1 = symptom1.getSelectedItem().toString();
                String symp2 = symptom2.getSelectedItem().toString();
                String symp3 = symptom3.getSelectedItem().toString();
                String symp4 = symptom4.getSelectedItem().toString();

                String intensity1=int1.getSelectedItem().toString();
                String intensity2=int2.getSelectedItem().toString();
                String intensity3=int3.getSelectedItem().toString();
                String intensity4=int4.getSelectedItem().toString();

                i.putExtra("symptom1", symp1);
                i.putExtra("symptom2", symp2);
                i.putExtra("symptom3", symp3);
                i.putExtra("symptom4", symp4);
                i.putExtra("intensity1",intensity1);
                i.putExtra("intensity2",intensity2);
                i.putExtra("intensity3",intensity3);
                i.putExtra("intensity4",intensity4);

                //i.putExtra("prediction", prediction);
                startActivity(i);
            }
        });
        /*Intent i = new Intent(MainActivity.this, Main2Activity.class);
        i.putExtra("Symp1", symp1);
        startActivity(i);*/
    }
}


